Remove twin.macro, use pure tailwindcss3
kamilkisiela/graphql-hive pull request #1256
Opened 2023-02-06 16:55 UTC by B2o5T

2023-02-06 16:57 UTC, B2o5T commented on packages/web/app/src/components/common/Navigation.tsx
> -          <div className="hive-release-notes" />
does this class is somewhere used?

2023-02-06 16:58 UTC, B2o5T commented on packages/web/app/src/components/project/migration-toast.tsx
> -        className="shrink-1 mr-2 self-center text-sm font-medium text-gray-300"
`shrink-1` not exist, seems typo

2023-02-07 00:21 UTC, enisdenjo approved these changes

2023-02-07 03:02 UTC, dotansimha commented on packages/web/app/src/components/common/Navigation.tsx
> -          <div className="hive-release-notes" />
I think it's unused?

2023-02-07 05:37 UTC, dotansimha commented
@B2o5T my impression so far:

### `Create Project` does not work

This button on the main org page:
<img width="241" alt="image" src="https://user-images.githubusercontent.com/3680083/217153018-60270d80-3a14-4a12-9023-a708e4aba84c.png">

is no longer functional; I'm not able to click on it at all. 

### Modals position

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/3680083/217153191-1c754a51-18ed-4312-beb6-f85fed1f9f99.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3680083/217153648-e9a24e18-25fe-4e68-87d6-3827e645f20a.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3680083/217153683-1ec321c1-ce2d-4b76-9252-e2c774f519bd.png">

seems a bit off, no longer centered 

 ### CDN `Connect` button is not working 

<img width="519" alt="image" src="https://user-images.githubusercontent.com/3680083/217156003-195f969f-8804-4ce0-9b2f-4875269f1ea3.png">

can't click at all 

> I tested all other screens and it looks the same as before ✅

2023-02-07 05:37 UTC, dotansimha requested changes
Please refer to my comment above.

2023-02-13 03:08 UTC, merged