1️⃣ refactor(services: rate-limit): migrate from fastify to @whatwg-node/server
kamilkisiela/graphql-hive pull request #1360
Opened 2023-02-13 12:36 UTC by YassinEldeeb

instead of #858 which got closed by accident

2023-02-20 08:52 UTC, ardatan commented on packages/services/rate-limit/src/router.ts
> +rateLimitRouter.all('/trpc/:path+', async (req: any) => {
```suggestion
rateLimitRouter.all('/trpc/:path+', responseWithTRPC)
```
We can pass this handler without an additional `async/await`, no?

2023-02-21 11:29 UTC, n1ru4l approved these changes

2023-02-21 11:51 UTC, ardatan approved these changes

2023-02-21 12:37 UTC, n1ru4l commented
I pushed this to https://github.com/kamilkisiela/graphql-hive/pull/1434 and integration tests fail.

2023-02-21 12:37 UTC, n1ru4l requested changes
Integration tests fail see https://github.com/kamilkisiela/graphql-hive/pull/1434

2023-11-05 09:57 UTC, dotansimha commented
Closing. This PR is outdated and we'll reconsider it later.

2023-11-05 09:57 UTC, closed without merging