Change schemacheck cli output
kamilkisiela/graphql-hive pull request #3862
Opened 2024-01-25 23:55 UTC by kongMina

### Background

### Description

### Checklist

- [ ] Input validation
- [ ] Output encoding
- [ ] Authentication management
- [ ] Session management
- [ ] Access control
- [ ] Cryptographic practices
- [ ] Error handling and logging
- [ ] Data protection
- [ ] Communication security
- [ ] System configuration
- [ ] Database security
- [ ] File management
- [ ] Memory management
- [ ] Testing

2024-01-31 09:18 UTC, n1ru4l approved these changes

2024-02-01 07:32 UTC, dotansimha approved these changes

2024-02-01 12:30 UTC, n1ru4l requested changes
these updates break existing integration tests, please update the integration tests that are affected by these changes

2024-02-21 13:45 UTC, n1ru4l approved these changes

2024-02-21 14:05 UTC, dotansimha commented
@n1ru4l can we merge this one? also @kamilkisiela

2024-02-21 14:36 UTC, merged