Draft: setting nav design
kamilkisiela/graphql-hive pull request #4241
Opened 2024-03-15 18:17 UTC by TuvalSimha

### Background

### Description

### Checklist

- [ ] Input validation
- [ ] Output encoding
- [ ] Authentication management
- [ ] Session management
- [ ] Access control
- [ ] Cryptographic practices
- [ ] Error handling and logging
- [ ] Data protection
- [ ] Communication security
- [ ] System configuration
- [ ] Database security
- [ ] File management
- [ ] Memory management
- [ ] Testing

2024-04-21 07:44 UTC, dotansimha commented
I think we need to rethink the sidebar title and icons. Maybe something like that? 

⚙️ General
🔑 Tokens
🧱 Schema Composition

2024-04-21 08:29 UTC, n1ru4l commented
If we use icons please icons without color and not built-in emojis that will look completly different based on the OS being used.

As for the seperations, I would even separate CDN access tokens and registry tokens to their own pages, as well as conditional breaking changes and base schemas.

2024-04-21 08:30 UTC, n1ru4l commented
I think the yellow underline might be a bit too agressive, we already have a similar menu for the user role management settings on the organisation level, we could mostly re-use these styles.

2024-04-22 15:53 UTC, kamilkisiela commented
> **Settings**
> Manage your XYZ
is no longer needed

2024-04-22 15:54 UTC, kamilkisiela commented
And let's not use icons

2024-04-22 15:56 UTC, kamilkisiela commented
@TuvalSimha you can check the sub-menu I did for members, because we already have such thing in Hive, now we will have 2 differently looking menus that serve the same purpose.

2024-04-29 12:41 UTC, n1ru4l commented
<img width="926" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/14338007/6bba02aa-fdec-4240-896e-abb6e700d6cc">

Let's also separate CDN access tokens and registry tokens to their own pages

https://github.com/kamilkisiela/graphql-hive/pull/4241#issuecomment-2067958416

2024-04-29 12:42 UTC, n1ru4l requested changes
see my two comments!

2024-04-30 17:45 UTC, TuvalSimha commented
@n1ru4l  @dotansimha @kamilkisiela 
Little bit confused 🤣

Lets make it clear:

(tab section | content page components)
1. General: Target Name Edit + GraphQL Endpoint URL + Delete Target
2. CDN: CDN Access Token
3. Tokens: Registry Access Tokens
4. Conditional Breaking Changes: Conditional Breaking Changes
5. Base Schema: Extend Base Schema

right?

2024-05-03 10:19 UTC, n1ru4l commented
@TuvalSimha Let's also drop the "shape"/frame around the single sections:

![image](https://github.com/kamilkisiela/graphql-hive/assets/14338007/19b7da11-78dd-4778-80b5-e0d2d2d5e439)

Instead, we can make it look more flat similar to GitHub and separate different sections through headings and spacings like GitHub settings:

![image](https://github.com/kamilkisiela/graphql-hive/assets/14338007/cc0e0e41-3eec-4e24-963b-6c1cf829bdce)

2024-05-05 14:56 UTC, TuvalSimha commented
So i worked on it, created new components for that to make sure all be with the same design.
You can watch the video below

https://github.com/kamilkisiela/graphql-hive/assets/37614975/6d0d2750-3203-45c0-98fd-e0f79dc4d484

Thoughts?

2024-05-05 14:58 UTC, TuvalSimha commented
> @dotansimha @kamilkisiela @n1ru4l
> 
> So i worked on it, created new components for that to make sure all be with the same design. You can watch the video below
> 
>  Screen.Recording.2024-05-05.at.17.53.48.mov 
> Thoughts?

Oh, and for this moment every sub page for Members without any main title (see the main title in Target setting) i can add if we want. Also, what about the organization settings design?

2024-05-20 12:28 UTC, kamilkisiela commented on packages/web/app/src/components/v2/modals/connect-schema.tsx
> +                page: 'general',
shouldn't this be `cdn`?

2024-06-04 11:15 UTC, merged