create target modal
kamilkisiela/graphql-hive pull request #4970
Opened 2024-06-13 13:10 UTC by TuvalSimha

### Background

### Description

### Checklist

- [ ] Input validation
- [ ] Output encoding
- [ ] Authentication management
- [ ] Session management
- [ ] Access control
- [ ] Cryptographic practices
- [ ] Error handling and logging
- [ ] Data protection
- [ ] Communication security
- [ ] System configuration
- [ ] Database security
- [ ] File management
- [ ] Memory management
- [ ] Testing

2024-06-30 11:52 UTC, dotansimha approved these changes

2024-07-02 10:45 UTC, dimaMachina commented on packages/web/app/.storybook/preview.js
> +};
Idk what a proper way to inject env variables (set `window.__ENV`) for the storybook, any suggestions?

2024-07-02 10:46 UTC, dimaMachina commented on packages/web/app/src/env/read.ts
>  }
https://github.com/kamilkisiela/graphql-hive/pull/5004/files#r1647826466

2024-07-10 09:13 UTC, kamilkisiela commented
![Screenshot 2024-07-10 at 10 55 07](https://github.com/kamilkisiela/graphql-hive/assets/8167190/6b724222-ef82-4b68-861d-7e4dfdf8f666)

Artifacts should not be part of the selectable options (the same applies to the other select component, contracts)
![Screenshot 2024-07-10 at 10 26 36](https://github.com/kamilkisiela/graphql-hive/assets/
![Screenshot 2024-07-10 at 10 21 48](https://github.com/kamilkisiela/graphql-hive/assets/8167190/2bb9d8a8-5d1f-41a6-882f-03d93ad2b665)
8167190/e276963f-4882-4b63-99a2-e3c811d81e46)

Emails are missing here and the spacing is missing
![Screenshot 2024-07-10 at 08 54 12](https://github.com/kamilkisiela/graphql-hive/assets/8167190/88dd3d5d-9335-4e5e-9a25-9fb7b03c4109)

Creating a registry token does not work.
When I click on "Read only" option or pretty much any option, it has no effect.
Selecting 'No access' should not make "Generate Token" button active.
https://github.com/kamilkisiela/graphql-hive/assets/8167190/02b7c531-ed02-433d-9458-bbadff31b702

I will stop my review here.

Do you think splitting the PR into smaller PRs or doing it view by view, not component by component as I proposed before makes sense?

2024-07-10 09:15 UTC, kamilkisiela requested changes
I commented what needs to be improved

2024-07-17 14:20 UTC, closed without merging