Drop modals from V2: Tabs component
kamilkisiela/graphql-hive pull request #5229
Opened 2024-07-15 16:42 UTC by TuvalSimha

2024-07-17 18:37 UTC, dimaMachina commented on packages/web/app/src/components/ui/tabs.tsx
> +const TabsListMenu = React.forwardRef<
```suggestion
const TabsList = React.forwardRef<
```
can it be similar to radix?

2024-07-17 18:37 UTC, dimaMachina commented on packages/web/app/src/components/ui/tabs.tsx
> +const TabsTriggerMenu = React.forwardRef<
```suggestion
const TabsTrigger = React.forwardRef<
```

2024-07-17 18:37 UTC, dimaMachina commented on packages/web/app/src/components/ui/tabs.tsx
> +        : null,
```suggestion
      hasBorder
        && 'radix-state-active:border-b-orange-500 border-b-2 border-b-transparent px-4 py-3 hover:border-b-orange-900',
```

2024-07-17 18:37 UTC, dimaMachina commented on packages/web/app/src/components/ui/tabs.tsx
> +const TabsContentMenu = React.forwardRef<
```suggestion
const TabsContent = React.forwardRef<
```

2024-07-17 18:38 UTC, dimaMachina commented on packages/web/app/src/components/ui/tabs.tsx
> +    className={cn(noPadding ? undefined : 'py-7', className)}
```suggestion
    className={cn(!noPadding && 'py-7', className)}
```

2024-07-17 18:39 UTC, dimaMachina commented on packages/web/app/src/stories/tabs.stories.tsx
> +            <a onClick={() => setPage(Page.Subscription)}>Subscription</a>
```suggestion
            <button onClick={() => setPage(Page.Members)}>Overview</button>
          </TabsTrigger>
          <TabsTrigger value={Page.Members} asChild>
            <button onClick={() => setPage(Page.Members)}>Members</button>
          </TabsTrigger>
          <TabsTrigger value={Page.Policy} asChild>
            <button onClick={() => setPage(Page.Policy)}>Policy</button>
          </TabsTrigger>
          <TabsTrigger value={Page.Settings} asChild>
            <button onClick={() => setPage(Page.Settings)}>Settings</button>
          </TabsTrigger>
          <TabsTrigger value={Page.Support} asChild>
            <button onClick={() => setPage(Page.Support)}>Support</button>
          </TabsTrigger>
          <TabsTrigger value={Page.Subscription} asChild>
            <button onClick={() => setPage(Page.Subscription)}>Subscription</button>
```

links should have `href` use `button` instead

2024-07-17 18:40 UTC, dimaMachina commented on packages/web/app/src/stories/tabs.stories.tsx
> +            <a onClick={() => setPage(Page.Subscription)}>Subscription</a>
```suggestion
            <button onClick={() => setPage(Page.Members)}>Overview</button>
          </TabsTriggerMenu>
          <TabsTriggerMenu value={Page.Members} asChild>
            <button onClick={() => setPage(Page.Members)}>Members</button>
          </TabsTriggerMenu>
          <TabsTriggerMenu value={Page.Policy} asChild>
            <button onClick={() => setPage(Page.Policy)}>Policy</button>
          </TabsTriggerMenu>
          <TabsTriggerMenu value={Page.Settings} asChild>
            <button onClick={() => setPage(Page.Settings)}>Settings</button>
          </TabsTriggerMenu>
          <TabsTriggerMenu value={Page.Support} asChild>
            <button onClick={() => setPage(Page.Support)}>Support</button>
          </TabsTriggerMenu>
          <TabsTriggerMenu value={Page.Subscription} asChild>
            <button onClick={() => setPage(Page.Subscription)}>Subscription</button>
```

2024-07-17 18:41 UTC, dimaMachina commented on packages/web/app/src/stories/tabs.stories.tsx
> +            <a onClick={() => setPage(Page.Subscription)}>Subscription</a>
also use `.map(...)` to DRY

2024-07-17 18:43 UTC, dimaMachina commented on packages/web/app/src/components/ui/tabs.tsx
> +    className={cn(noPadding ? undefined : 'py-7', className)}
personally, I don't like I don't like `props` aka `noPadding`, `noMargin`, you have already `className` and padding can be removed with `p-0` cc @kamilkisiela @n1ru4l

2024-07-17 18:46 UTC, dimaMachina commented on packages/web/app/src/components/ui/tabs.tsx
> +const TabsListMenu = React.forwardRef<
maybe use `variant="..."` instead since there is 2 types of tabs

2024-07-17 18:46 UTC, dimaMachina requested changes
overview is not clickable

https://github.com/user-attachments/assets/aff26079-9e38-42c7-aad2-86da69e5b933

2024-07-18 07:22 UTC, TuvalSimha commented
@dimaMachina 

I changed it to use `cva` and `variants`, this looks much better now. What do you think?

2024-07-23 07:23 UTC, TuvalSimha commented on packages/web/app/src/components/ui/tabs.tsx
> +      !noPadding && tabsContentVariants({ variant: 'default' }),
Done :)

2024-08-15 16:07 UTC, saihaj approved these changes

2024-08-15 16:08 UTC, saihaj requested changes
Hmm actually @dimaMachina comment around not being able to click `overview` on storybook is stil valid.

On the actual app usage I don't see this issue. So something weird going on with storybook 😢 

https://github.com/user-attachments/assets/f506c5c2-0d68-4b0c-ab72-980a0fc0da6c

2024-08-15 16:10 UTC, saihaj approved these changes
Actually you are good. The link in the PR description is pointing to old preview. If I test latest storybook build it works as expected.

2024-08-18 14:33 UTC, merged