revamp tracing/monitoring docs
kamilkisiela/graphql-hive pull request #5579
Opened 2024-09-05 17:22 UTC by dotansimha

2024-09-05 17:30 UTC, ardatan approved these changes

2024-09-05 17:37 UTC, saihaj approved these changes
I suppose for SEO having a separate page works best 🤔 but I do see how it is much more simpler to navigate from user perspective

2024-09-06 08:03 UTC, EmrysMyrddin commented on packages/web/docs/src/pages/docs/gateway/features/monitoring-tracing.mdx
> +  }
Metrics are now under a `metrics` field
```suggestion
  prometheus: {
    // Enable the metrics you want to expose
    // The following represent the default config of the plugin.
    metrics: {
      graphql_gateway_fetch_duration: true,
      graphql_gateway_subgraph_execute_duration: true,
      graphql_gateway_subgraph_execute_errors: true,
      graphql_envelop_deprecated_field: true,
      graphql_envelop_request: true,
      graphql_envelop_request_duration: true,
      graphql_envelop_request_time_summary: true,
      graphql_envelop_phase_parse: true,
      graphql_envelop_phase_validate: true,
      graphql_envelop_phase_context: true,
      graphql_envelop_error_result: true,
      graphql_envelop_phase_execute: true,
      graphql_envelop_phase_subscribe: true,
      graphql_envelop_schema_change: true,
      graphql_yoga_http_duration: true,
    }
  }
```

2024-09-06 08:19 UTC, n1ru4l approved these changes

2024-09-06 08:20 UTC, EmrysMyrddin approved these changes
I've pushed a commit to fix the missing `metrics` option and remove references to old option name.

Looks amazing !

2024-09-06 08:27 UTC, n1ru4l requested changes
please move this document out of features to the top level under gateway

2024-09-06 10:52 UTC, dotansimha commented
@n1ru4l fixed :)

2024-09-06 11:00 UTC, merged