Support log level and request logs
kamilkisiela/graphql-hive pull request #612
Opened 2022-11-08 01:53 UTC by rperryng

Adds support for:
1. configuring the logger level via the `LOG_LEVEL` env var
2. request logging.  Can be disabled with `LOG_DISABLE_REQUEST_LOGGING`

example from dockerrun:
```
server_1          | {"level":30,"time":1667871767331,"pid":1,"hostname":"b18cd7df7dd1","msg":"[200] (172.19.0.3) POST /graphql"}
```

2022-11-14 15:50 UTC, rperryng commented
@kamilkisiela any thoughts :)?

2022-11-14 15:58 UTC, n1ru4l commented
@kamilkisiela Thoughts on the flag for disabling request logging? I think request logging should be determined via the log level (`info`) and not an additional option.

2022-11-15 09:19 UTC, kamilkisiela commented
I think we could show operation's name as well and the value of the `request_id` header and I guess making it use `info` level is fine.

I know I said it should be opt-in but on the other hand it does not bring much noise to the logs, so maybe having it enabled by default (with no option to opt-out) is actually the best option. If you all agree, then I will create a PR to your PR @rperryng to remove the flag `LOG_DISABLE_REQUEST_LOGGING` flag.

2022-11-15 15:16 UTC, rperryng commented
I removed the flag to disable request logging :).

With latest changes, the log message now looks like so:

```
server_1          | {"level":30,"time":1668522424590,"pid":1,"hostname":"5b5d04c96b55","msg":"[200] (172.19.0.11) POST /graphql 'organizationActivities' (+6CDHcG1SB+PXYOPpJiD1A/0000000004)"}
```

Is this close to what you had in mind @kamilkisiela ?

2022-11-16 10:20 UTC, n1ru4l commented on packages/services/emails/src/environment.ts
> +    level: log.LOG_LEVEL ?? 'debug',
I think the default fallback log level should be info

2022-11-16 10:21 UTC, n1ru4l commented on packages/services/emails/src/environment.ts
> +    .optional(),
these should be wrapped in `emptyString()` so that `""` is also interpreted as an empty value rather than raise a runtime error.

2022-11-16 10:26 UTC, n1ru4l requested changes
I added two small comments that apply to all the files where the logging is parsed from the env variables

2022-11-16 14:27 UTC, rperryng commented
@n1ru4l thanks for your feedback, it should be addressed now - let me know if I misunderstood anything

2022-11-21 16:42 UTC, kamilkisiela commented
@rperryng https://github.com/rperryng/graphql-hive/pull/1 

![](https://media.giphy.com/media/7pHTiZYbAoq40/giphy.gif)

2022-11-21 17:04 UTC, rperryng commented
@kamilkisiela thanks!  merged your changes 🙂 

I figured there must have been a way to avoid re-parsing since all the envelop servers are already doing it, but yeah, wasn't sure how to slide it in the current config 😅.  Maybe I can give it a look when graphql-hive has moved off of fastify

2022-11-22 10:52 UTC, merged